### PR TITLE
Add two tests for sprint synchronization (#80)

### PR DESCRIPTION
**Pull request by mjkrause**

### CODE REVIEW

**Review by cricketsloan — CHANGES_REQUESTED** [review]
In line 183 of sync.py, the logic has been added that if the Zenhub issue.milestone == A and the Jira issue.milestone == B, you would generate an error instead of considering Zenhub the master and updating the Jira issue to match the zenhub issue.    I do not think that would be the behavior of a primary(master) copy.  A primary (master) copy should dictate what the replica (slave) copy's values are.

**Comment by mjkrause** [comment]
There are three scenarios for the sprint synchronization:

1. Both master and slave have a sprints with identical names. Code and tests cover that already.
2. The ticket in master is associated with _sprint A_, but in the slave it is associated with _sprint B_. But a sprint named _sprint A_ exists in the slave. In that case update the ticket such that it is associated with _sprint A_ in slave.
3.  The ticket in master is associated with _sprint A_, but in the slave it is associated with _sprint B_. But no sprint named _sprint A_ exists in the slave. Then, as stated in #49, no new _sprint A_ should be created in the slave, only a warning is logged, and loop iteration continues.

**Review by cricketsloan — COMMENTED** [review]
My requests have been satisfied.  @emlys can you review this in context with your added code to have JIRA as the primary and Zenhub as the replica.  I did not have time to look, but I expect there might be divergence in the logic for the two methods.  

@mjkrause can you update the documentation to clarify that there is no mirror sync for sprint-milestone only 1-way sync

**Comment by mjkrause** [comment]
> @mjkrause can you update the documentation to clarify that there is no mirror sync for sprint-milestone only 1-way sync
Okay.

**Review by cricketsloan — CHANGES_REQUESTED** [review]
In sync.py    line 195, the error message is not clear, it still represents the old logic.  I believe it should say:  "Sync sprint: Sprint name {source.milestone_name} does not exist in the destination.  Existing sprint name in destination {dest.sprint_name} will be left untouched  '            
                            logger.warning(
                            f'Sync sprint: Sprint name {dest.sprint_name} does not match '
                            f'milestone name {source.milestone_name} - sprint and milestone names must match!')

**Comment by cricketsloan** [comment]
Line 231 in sync.py also needs to be changed

**Review by cricketsloan — APPROVED** [review]

**Pull request merged**
